[tool.poetry]
name = "scores_app"
version = "1.0.0"
description = "API de scores: calcula y persiste la utilidad de una oferta."
authors = [
  "ga.gonzalezo1"
]
license = "MIT"
readme = "README.md"
package-mode = false
packages = [{include = "*", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "~3.11"
fastapi = "~0.115.12"
uvicorn = "~0.27.1"
python-dotenv = "~1.0.1"
pydantic = "~2.6.1"
pydantic-settings = "~2.1.0"
sqlalchemy = {version = "~2.0.28", extras = ["asyncio"]}
asyncpg = "~0.29.0"
greenlet = "~3.1"

[tool.poetry.group.dev.dependencies]
black = "~25.1.0"
ruff = "~0.11.12"
bandit = "~1.8.3"
flake8 = "~7.2.0"
isort = "~6.0.1"
pytest = "~8.4.0"
pytest-cov = "~6.1.1"
pytest-mock = "~3.14.1"
pytest-env = "~1.1.5"
pytest-asyncio = "~0.23.5"
httpx = "~0.27.0"
faker = "~37.3.0"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.bandit]
exclude_dirs = ["./tests"]
skips = ["B101"]

[tool.pydoclint]
style = "google"
arg-type-hints-in-docstring = true
check-return-types = false
check-yield-types = false

[tool.ruff]
src = ["src"]
fix = true
lint.ignore = ["B008"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 20

[tool.pytest.ini_options]
python_files = "test_*.py"
pythonpath = "src"
testpaths = [
  "tests"
]
asyncio_mode = "auto"
env = [
  "LOG_LEVEL = INFO",
  "DB_HOST = localhost",
  "DB_PORT = 5432",
  "DB_NAME = scores_db_test",
  "DB_USER = test",
  "DB_PASSWORD = test"
]
