services:
  orchestrator_app:
    build:
      context: .
      target: runner
    ports:
      - "30005:30005"
    environment:
      APP_PORT: 30005
      USERS_APP_URL: http://host.docker.internal:30000
      POSTS_APP_URL: http://host.docker.internal:30001
      ROUTES_APP_URL: http://host.docker.internal:30002
      OFFERS_APP_URL: http://host.docker.internal:30003
      SCORES_APP_URL: http://host.docker.internal:30004
      HTTP_TIMEOUT_SECONDS: "3.0"
      HTTP_MAX_RETRIES: "1"
    extra_hosts:
      - "host.docker.internal:host-gateway"
