from enum import Enum


class AirportCode(str, Enum):
    ABC = "ABC"
    ACE = "ACE"
    AEP = "AEP"
    AFA = "AFA"
    AGP = "AGP"
    ALC = "ALC"
    AMA = "AMA"
    AMS = "AMS"
    ANF = "ANF"
    AOL = "AOL"
    ARI = "ARI"
    ARN = "ARN"
    ASB = "ASB"
    ASU = "ASU"
    ATH = "ATH"
    AUA = "AUA"

    BBA = "BBA"
    BCN = "BCN"
    BHI = "BHI"
    BIN = "BIN"
    BIO = "BIO"
    BJX = "BJX"
    BJZ = "BJZ"
    BOD = "BOD"
    BOG = "BOG"
    BPM = "BPM"
    BRC = "BRC"
    BSL = "BSL"
    BST = "BST"
    BUD = "BUD"
    BYJ = "BYJ"

    CCC = "CCC"
    CCP = "CCP"
    CCS = "CCS"
    CDG = "CDG"
    CDT = "CDT"
    CGN = "CGN"
    CLO = "CLO"
    CLX = "CLX"
    CMN = "CMN"
    CNQ = "CNQ"
    COC = "COC"
    COR = "COR"
    CQM = "CQM"
    CTC = "CTC"
    CUE = "CUE"
    CUU = "CUU"
    CVU = "CVU"
    CWB = "CWB"

    DAY = "DAY"
    DJE = "DJE"
    DME = "DME"
    DOH = "DOH"
    DXB = "DXB"

    EAP = "EAP"
    EAS = "EAS"
    EDI = "EDI"
    EGE = "EGE"
    EIN = "EIN"
    ENO = "ENO"
    EOH = "EOH"
    EPA = "EPA"
    ESR = "ESR"
    EZE = "EZE"

    FAO = "FAO"
    FBD = "FBD"
    FCO = "FCO"
    FDO = "FDO"
    FLA = "FLA"
    FLR = "FLR"
    FLW = "FLW"
    FMA = "FMA"
    FNC = "FNC"
    FOR = "FOR"
    FRA = "FRA"
    FRS = "FRS"
    FTE = "FTE"
    FUN = "FUN"

    GDL = "GDL"
    GHU = "GHU"
    GIB = "GIB"
    GPO = "GPO"
    GRU = "GRU"
    GRW = "GRW"
    GRX = "GRX"
    GUA = "GUA"
    GYE = "GYE"

    HAJ = "HAJ"
    HAM = "HAM"
    HAV = "HAV"
    HBX = "HBX"
    HEA = "HEA"
    HEL = "HEL"
    HGL = "HGL"
    HHN = "HHN"
    HIR = "HIR"
    HKG = "HKG"
    HMO = "HMO"
    HND = "HND"
    HNL = "HNL"
    HOG = "HOG"
    HOR = "HOR"
    HOU = "HOU"
    HUX = "HUX"

    IBZ = "IBZ"
    ICN = "ICN"
    IGR = "IGR"
    INV = "INV"
    IPC = "IPC"
    IQQ = "IQQ"
    IRJ = "IRJ"
    IST = "IST"
    IVL = "IVL"

    JAA = "JAA"
    JER = "JER"
    JFK = "JFK"
    JKL = "JKL"
    JSR = "JSR"
    JUJ = "JUJ"

    KBL = "KBL"
    KDH = "KDH"
    KEF = "KEF"
    KGD = "KGD"

    LAD = "LAD"
    LAS = "LAS"
    LAX = "LAX"
    LCE = "LCE"
    LCG = "LCG"
    LEI = "LEI"
    LEU = "LEU"
    LGG = "LGG"
    LGS = "LGS"
    LGW = "LGW"
    LHR = "LHR"
    LIM = "LIM"
    LIR = "LIR"
    LIS = "LIS"
    LPA = "LPA"
    LPB = "LPB"
    LTN = "LTN"
    LUQ = "LUQ"

    MAD = "MAD"
    MCO = "MCO"
    MCS = "MCS"
    MDE = "MDE"
    MDQ = "MDQ"
    MDX = "MDX"
    MDZ = "MDZ"
    MEC = "MEC"
    MEX = "MEX"
    MFM = "MFM"
    MGA = "MGA"
    MIA = "MIA"
    MKC = "MKC"
    MLH = "MLH"
    MLN = "MLN"
    MPN = "MPN"
    MTY = "MTY"
    MUC = "MUC"
    MVD = "MVD"
    MXP = "MXP"
    MZR = "MZR"

    NAP = "NAP"
    NIC = "NIC"
    NLK = "NLK"
    NLU = "NLU"
    NRT = "NRT"

    OPO = "OPO"
    ORA = "ORA"
    ORD = "ORD"
    ORK = "ORK"
    ORY = "ORY"
    OYA = "OYA"

    PBR = "PBR"
    PDP = "PDP"
    PDL = "PDL"
    PHL = "PHL"
    PIX = "PIX"
    PJC = "PJC"
    PNA = "PNA"
    PRA = "PRA"
    PRQ = "PRQ"
    PSY = "PSY"
    PTY = "PTY"
    PUJ = "PUJ"
    PUQ = "PUQ"
    PXO = "PXO"

    QGY = "QGY"
    QRC = "QRC"
    QSA = "QSA"

    RAK = "RAK"
    RBA = "RBA"
    RES = "RES"
    REU = "REU"
    REX = "REX"
    RGA = "RGA"
    RHD = "RHD"
    RLO = "RLO"
    RMU = "RMU"
    ROS = "ROS"
    RRG = "RRG"
    RSA = "RSA"
    RTB = "RTB"
    RUH = "RUH"

    SAL = "SAL"
    SAP = "SAP"
    SBZ = "SBZ"
    SCL = "SCL"
    SCQ = "SCQ"
    SCU = "SCU"
    SDE = "SDE"
    SDQ = "SDQ"
    SFM = "SFM"
    SFN = "SFN"
    SFO = "SFO"
    SIN = "SIN"
    SJO = "SJO"
    SJZ = "SJZ"
    SKG = "SKG"
    SLA = "SLA"
    SLM = "SLM"
    SMA = "SMA"
    SNU = "SNU"
    SUF = "SUF"
    SVO = "SVO"
    SVQ = "SVQ"
    SXB = "SXB"
    SYD = "SYD"

    TER = "TER"
    TEV = "TEV"
    TFN = "TFN"
    TFS = "TFS"
    TGD = "TGD"
    TGU = "TGU"
    THF = "THF"
    TLS = "TLS"
    TLV = "TLV"
    TPE = "TPE"
    TRS = "TRS"
    TSE = "TSE"
    TTG = "TTG"
    TUN = "TUN"
    TUR = "TUR"

    UAQ = "UAQ"
    UIO = "UIO"
    USH = "USH"
    UZU = "UZU"

    VCP = "VCP"
    VDC = "VDC"
    VDM = "VDM"
    VGO = "VGO"
    VIE = "VIE"
    VKO = "VKO"
    VLC = "VLC"
    VLL = "VLL"
    VME = "VME"
    VVI = "VVI"

    WLG = "WLG"

    XPL = "XPL"
    XRY = "XRY"

    YFB = "YFB"
    YHU = "YHU"
    YHZ = "YHZ"
    YOW = "YOW"
    YQB = "YQB"
    YRB = "YRB"
    YUL = "YUL"
    YVM = "YVM"
    YVR = "YVR"
    YWG = "YWG"
    YYC = "YYC"
    YYY = "YYY"
    YYZ = "YYZ"

    ZAG = "ZAG"
    ZAZ = "ZAZ"


Airport_Code = AirportCode
