name: Evaluador Pruebas Unitarias
# Actualice este pipeline si usted decide trabajar en una tecnología diferente a Python.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  users_app:
    runs-on: ubuntu-latest
    name: Verify users_app
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.1.1
      - name: Run linter checkers in users_app
        run: make lintcheck DIR=users_app
      - name: Run unit tests
        run: make unittest DIR=users_app

  posts_app:
    runs-on: ubuntu-latest
    name: Verify posts_app
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.1.1
      - name: Run linter checkers in posts_app
        run: make lintcheck DIR=posts_app
      - name: Run unit tests
        run: make unittest DIR=posts_app

  offers_app:
    runs-on: ubuntu-latest
    name: Verify offers_app
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.1.1
      - name: Run linter checkers in offers_app
        run: make lintcheck DIR=offers_app
      - name: Run unit tests
        run: make unittest DIR=offers_app

  routes_app:
    runs-on: ubuntu-latest
    name: Verify routes_app
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.1.1
      - name: Run linter checkers in routes_app
        run: make lintcheck DIR=routes_app
      - name: Run unit tests
        run: make unittest DIR=routes_app

  orchestrator_app:
    runs-on: ubuntu-latest
    name: Verify orchestrator_app
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.1.1
      - name: Run linter checkers in orchestrator_app
        run: make lintcheck DIR=orchestrator_app
      - name: Run unit tests
        run: make unittest DIR=orchestrator_app
